training_config:
  n_epochs: 1000
  patience: 100
  store_everything: True
model_config:
  class: models.LyingGCN2
  params:
    n_layers: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    num_hidden_channels: [5, 10, 20]
    act_fun: [tanh, relu]
    add_self_loops: True
    concat_ego_neigh_embs: False
    p_dropout: 0
    p_input_dropout: 0
    alpha: 0.1 #[ 0.1, 0.2, 0.5 ]
    theta: 1 #[ 0.5, 1, 1.5 ]
    skip_connections: True
    classifier_at_each_layer: False
optimiser_config:
  class: torch.optim.Adam
  params:
    lr: 0.01
    weight_decay: 0